[libraries]
annotations = { group = "com.google.code.findbugs", name = "jsr305", version = "3.0.2" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.11.0" }
netty = { group = "io.netty", name = "netty-all", version = "4.1.114.Final" }

[bundles]
common = [
    "annotations",
    "gson",
    "netty"
]
